#!/bin/sh

#SBATCH --ntasks=100
##SBATCH --exclusive
#SBATCH --job-name=qr_julia
##SBATCH --partition=ivyb
##SBATCH --partition=westmere
##SBATCH --partition=mkolar
##SBATCH --qos=mkolar
#SBATCH --time=1-12:00:00
 
module load parallel

parallel -j $SLURM_NTASKS --joblog __$SLURM_JOB_NAME.runtask.log --resume srun --exclusive -N1 -n1 --error=/scratch/midway/mkolar/output/$SLURM_JOB_NAME.err.{1}.{2}.{3} --output=/scratch/midway/mkolar/output/$SLURM_JOB_NAME.out.{1}.{2}.{3} juliaGIT src/qr_path.jl /scratch/midway/mkolar/qr1 {1} {2} {3} ::: {1..500} ::: {2..2} ::: {1..1}

#parallel -j $SLURM_NTASKS --joblog __$SLURM_JOB_NAME.runtask.log --resume srun --exclusive -N1 -n1 --error=/scratch/midway/mkolar/output/$SLURM_JOB_NAME.err.{1}.{2}.{3} --output=/scratch/midway/mkolar/output/$SLURM_JOB_NAME.out.{1}.{2}.{3} juliaGIT sims/generate_data.jl /scratch/midway/mkolar/qr1/data {1} {2} {3} ::: {1..500} ::: {2..2} ::: {1..1}
