#!/bin/sh

#SBATCH --ntasks=125
##SBATCH --exclusive
#SBATCH --job-name=qr
##SBATCH --partition=ivyb
##SBATCH --partition=westmere
##SBATCH --partition=mkolar
##SBATCH --qos=mkolar
#SBATCH --time=1-12:00:00
 
module load parallel

#parallel -j $SLURM_NTASKS --joblog __$SLURM_JOB_NAME.genData.runtask.log --resume srun --exclusive -N1 -n1 --error=/scratch/midway/mkolar/output/$SLURM_JOB_NAME.err.{1}.{2}.{3} --output=/scratch/midway/mkolar/output/$SLURM_JOB_NAME.out.{1}.{2}.{3} juliaGIT sims/generate_data.jl /scratch/midway/mkolar/qr/data {1} {2} {3} ::: {1..500} ::: {2..2} ::: {3..3}

#parallel -j $SLURM_NTASKS --joblog __$SLURM_JOB_NAME.run.runtask.log --resume srun --exclusive -N1 -n1 --error=/scratch/midway/mkolar/output/$SLURM_JOB_NAME.err.{1}.{2}.{3} --output=/scratch/midway/mkolar/output/$SLURM_JOB_NAME.out.{1}.{2}.{3} juliaGIT sims/qr_path.jl /scratch/midway/mkolar/qr  {1} {2} {3} ::: {1..500} ::: {2..2} ::: {1..3}


parallel -j $SLURM_NTASKS --joblog __$SLURM_JOB_NAME.runtask.log --resume srun --exclusive -N1 -n1 --error=/scratch/midway/mkolar/output/$SLURM_JOB_NAME.err.{1}.{2}.{3} --output=/scratch/midway/mkolar/output/$SLURM_JOB_NAME.out.{1}.{2}.{3} juliaGIT sims/sparsity_function_oracle.jl /scratch/midway/mkolar/qr /scratch/midway/mkolar/qr_spF {1} {2} {3} ::: {1..500} ::: {2..2} ::: {1..3}


